FROM --platform=linux/amd64 node:lts-alpine3.17 AS deps

WORKDIR /app

COPY package.json ./
COPY prisma ./

RUN npm install
RUN npx prisma generate

CMD [ "npx", "prisma", "migrate", "deploy", "--preview-feature" ]
