networks:
  proxy:
    external: true

services:
  app:
    image: wellness-app
    environment:
      - DATABASE_URL=
      - EMAIL_SERVER_HOST=
      - EMAIL_SERVER_PORT=
      - EMAIL_SERVER_USER=
      - EMAIL_SERVER_PASSWORD=
      - EMAIL_SERVER_FROM=
      - EMAIL_NOTIFY_ADDRESS=
      - AUTH_URL=
      - LISTEN_ADDR=0.0.0.0:3000
    networks:
      - proxy
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.wellness.entryPoints: https
      traefik.http.routers.wellness.tls: true
      traefik.http.routers.wellness.rule: Host(``)
      traefik.http.services.wellness.loadbalancer.server.port: 3000
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:16.10-alpine
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  cron:
    image: wellness-app
    environment:
      - POSTGRES_PASSWORD=
      - EMAIL_SERVER_HOST=
      - EMAIL_SERVER_PORT=
      - EMAIL_SERVER_USER=
      - EMAIL_SERVER_PASSWORD=
      - EMAIL_SERVER_FROM=
      - EMAIL_NOTIFY_ADDRESS=
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "echo '0 2 * * * /app/cleanup >> /var/log/cron.log 2>&1' > /etc/crontabs/root &&
             echo '0 0 1/1 * * /app/remainder >> /var/log/cron.log 2>&1' >> /etc/crontabs/root &&
             crond -f -l 2"
    networks:
      - default
