r---
name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          echo "Using $(docker -v)"

          echo "::group::Logging into the GitHub Container registry (ghcr.io) ..."
          echo "${secrets.GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          echo "::endgroup::"

          export IMAGE_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
          export IMAAGE_TAG=ghcr.io/${{github.repository_owner}}/${{IMAGE_NAME}}:latest
          
          docker build . --tag ${{IMAGE_TAG}} \
          --build-arg NEXT_PUBLIC_PUSHER_APP_KEY=${{PUSHER_APP_KEY}}\
          --build-arg NEXT_PUBLIC_PUSHER_APP_CLUSTER=${{PUSHER_APP_CLUSTER}} \
          --build-arg NEXT_PUBLIC_PUSHER_APP_HOST=${{PUSHER_APP_HOST}} \
          --build-arg NEXT_PUBLIC_PUSHER_APP_PORT=${{PUSHER_APP_PORT}} \
          --build-arg NEXT_PUBLIC_PUSHER_APP_USE_TLS=${{PUSHER_APP_USE_TLS}}

          docker push ${{IMAGE_TAG}}
